import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { FaGraduationCap, FaUserGraduate, FaEnvelope } from "react-icons/fa6";
//import components
import Layout from "@/components/Layout";
import Deptnav from "@/components/navigation/Deptnav";
import AnimatedText from "@/components/AnimatedText";
import AnimatedTextWord from "@/components/AnimatedTextWord";
import Banner from "@/components/banner/Banner";
import Facultycard from "@/components/Facultycard";
import News from "@/components/banner/News";
import Slidertext3d from "@/components/banner/Slidertext3d";
//import dictionaries
import { csebanner } from "@/dictionary/Bannerlist";
import { cselinks, csephotos } from "@/dictionary/CSELinks";
import { newslinks } from "@/dictionary/Newslinks";

//import images
import placement1 from "@/assets/images/placement.png";
import a1 from "@/assets/images/accreditation/capgemini.png";
import a2 from "@/assets/images/accreditation/cisco.png";
import a3 from "@/assets/images/accreditation/cyient.png";
import a4 from "@/assets/images/accreditation/google.png";
import a5 from "@/assets/images/accreditation/tcs.png";
import a6 from "@/assets/images/accreditation/techmahindra.png";
import a7 from "@/assets/images/accreditation/wipro.png";

const cse = () => {
  return (
    <>
      <Head>
        <title>AOT | CSE</title>
        <meta name="description" content="Generated by me" />
      </Head>
      <Deptnav links={cselinks} />
      <main className="flex w-full flex-col items-center justify-center z-0">
        <Banner sliderItems={csebanner} />
        <Layout className="!pt-8">
          <div
            id="academics"
            className="flex flex-wrap rounded-2xl pt-4 px-4 w-full "
          >
            <div>
              <p className="pb-4 font-sans font-medium text-lg">
                &emsp;&emsp;&emsp;Since 2003, we aim to deliver high-quality
                professional education in the field of Computer Science. Our
                academic program offers various specialisations in Computer
                Science and Engineering. We focus on enabling students to apply
                their education effectively to solve real-world problems.
                Additionally, we endeavor to establish strong connections with
                leading industries on a global scale.
              </p>
            </div>
            <AnimatedText
              text="Academics"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <div>
              <AnimatedText
                text="Academic Programmes"
                className="!text-2xl text-start font-serif !text-[hsl(232,47%,28%)] italic"
              />
              <li className="pb-4 font-serif font-bold text-lg italic ml-4">
                &nbsp;4 years B.Tech programme in Computer Science &
                Engineering.
              </li>
              <AnimatedText
                text="HOD Details"
                className="!text-2xl text-start font-serif !text-[hsl(232,47%,28%)] italic"
              />
              <div className="flex gap-4 ml-3 my-1">
                <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1 rounded-[50%]">
                  <FaGraduationCap className="text-2xl text-white" />
                </div>
                <p className="text-xl font-serif align-middle font-semibold text-[hsl(232,47%,28%)]">
                  Prof. Prosenjit Das
                </p>
              </div>
              <div className="flex gap-4 ml-3 my-1">
                <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1.5 rounded-[50%]">
                  <FaEnvelope className="text-xl text-white" />
                </div>
                <Link
                  href="mailto:hod_cse@aot.edu.in"
                  target="_blank"
                  className="text-xl font-serif align-middle font-semibold text-[hsl(232,47%,28%)]"
                >
                  hod_cse@aot.edu.in
                </Link>
              </div>
            </div>
          </div>
          <div
            id="infrastructure"
            className="flex mt-2 flex-wrap rounded-2xl p-4 w-full"
          >
            <AnimatedText
              text="Infrastructure"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <div>
              <div className="pb-1 font-sans font-medium text-lg">
                <ul style={{ listStyleType: "disc" }}>
                  <li className="p-1.5">
                    Souranil Sarkar (3rd yr EE) won 1st position in
                    Rabindra-Sangeet, Najrool Geeti & Elocution in the
                    state-level intra-WBPDCL cultural meet organized by BTPS
                    Recreation Club in 2017.
                  </li>
                  <li className="p-1.5">
                    Saikat Dutta (3rd yr ECE) cleared the first round of the
                    national dance competition Dance India Dance, 2015.
                  </li>
                  <li className="p-1.5">
                    Rwitam Bandyopadhyay (4th yr CSE) got 7th position in India
                    on Guitar, a National level guitar competition organised by
                    Blade & powered by DigiTech, December 2013 – January 2014.
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div id="placements">
            <AnimatedText
              text="Placements"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <div className="grid grid-cols-2 lg:grid-cols-1 gxl:gap-1 gap-8 mx-4">
              <div className="p-3 flex gxl:justify-evenly justify-end llg:hidden">
                <div className="relative  ">
                  <div className="absolute bg-yellow-500/30 sm:left-8 mmd:-left-10 top-8 rounded-t-[50%] opacity-70 filter blur-xl h-[46vh] w-[50vw] "></div>
                  <div>
                    <Image
                      className="w-fit h-[50vh] bg-transparent mix-blend-multiply "
                      src={placement1}
                      alt=""
                    />
                  </div>
                </div>
              </div>
              <div className="relative p-3">
                <div className="absolute top-0 xs:hidden smmy:left-[5rem] left-[45vw] llg:left-[5rem] w-60 h-60 bg-purple-300/60 rounded-full mix-blend-multiply filter blur-2xl animate-blob"></div>
                <div className="absolute top-0 xs:hidden smmy:right-[5rem] right-[40vw] llg:right-[5rem] w-60 h-60 bg-yellow-300/60 rounded-full mix-blend-multiply filter blur-2xl animate-blob"></div>
                <div className="absolute top-28 xs:hidden smmy:left-44 left-[40vw] llg:left-44 w-60 h-60 bg-pink-300/60 rounded-full mix-blend-multiply filter blur-2xl animate-blob"></div>
                <div>
                  <div className="">
                    <AnimatedTextWord
                      text="&ldquo;Focus&emsp;Diligence&emsp;Consistency&rdquo;"
                      className="text-3xl sm:text-2xl sm:pb-2 text-accent inline text-center font-bold font-serif italic pt-3"
                    />
                  </div>
                  <div>
                    <div className="flex gap-4 my-3">
                      <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1.5 rounded-[50%]">
                        <FaGraduationCap className="text-3xl sm:text-2xl text-white" />
                      </div>
                      <p className="text-2xl sm:text-xl font-serif p-1 font-[550] text-[hsl(232,47%,28%)]">
                        <span className="text-[32px]  sm:text-[28px] font-bold font-serif">
                          45+&nbsp;
                        </span>
                        Top Companies
                      </p>
                    </div>
                    <div className="flex gap-4 my-3">
                      <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1.5 rounded-[50%]">
                        <FaGraduationCap className="text-3xl sm:text-2xl text-white" />
                      </div>
                      <p className="text-2xl sm:text-xl font-serif p-1 font-[550] text-[hsl(232,47%,28%)]">
                        <span className="text-[32px]  sm:text-[28px] font-bold font-serif">
                          520+&nbsp;
                        </span>
                        Job Offers
                      </p>
                    </div>
                    <div className="flex gap-4 my-3">
                      <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1.5 rounded-[50%]">
                        <FaGraduationCap className="text-3xl sm:text-2xl text-white" />
                      </div>
                      <p className="text-2xl sm:text-xl font-serif p-1 font-[550] text-[hsl(232,47%,28%)]">
                        <span className="text-[32px] sm:text-[28px] font-bold font-serif">
                          Rs.63 Lakhs&nbsp;
                        </span>
                        Highest Salary
                      </p>
                    </div>
                    <div className="flex gap-4 my-3">
                      <div className="bg-[hsl(232,47%,28%)] h-fit w-fit p-1.5 rounded-[50%]">
                        <FaGraduationCap className="text-3xl sm:text-2xl text-white" />
                      </div>
                      <p className="text-2xl sm:text-xl font-serif p-1 font-[550] text-[hsl(232,47%,28%)]">
                        <span className="text-[32px] sm:text-[28px] font-bold font-serif">
                          Rs.8 Lakhs&nbsp;
                        </span>
                        average CTC
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="p-3 flex gxl:justify-evenly justify-end lg:hidden">
                <div className="relative  ">
                  <div className="absolute bg-yellow-500/30 left-8 top-8 rounded-t-[50%] opacity-70 filter blur-xl h-[46vh] w-[46vh]"></div>
                  <div>
                    <Image
                      className="w-fit h-[50vh] bg-transparent mix-blend-multiply "
                      src={placement1}
                      alt=""
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-wrap rounded-2xl p-2 w-full">
              <AnimatedText
                text="Our Recruiters"
                className="!text-3xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
              />
              <div>
                <div className="grid gap-8 xs:grid-cols-1 smmy:grid-cols-2 lg:grid-cols-3 grid-cols-4 items-center  p-4 mt-1.5">
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-62">
                      <Image src={a1} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-20">
                      <Image src={a2} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-60">
                      <Image src={a3} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-56">
                      <Image src={a4} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-60">
                      <Image src={a5} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="xs:w-56 w-62">
                      <Image src={a6} alt="" />
                    </div>
                  </div>
                  <div className=" rounded-3xl p-3 flex justify-center cursor-pointer shadow-news-shadow hover:shadow-inside-shadow hover:scale-90 transition-all ease-in-out duration-300">
                    <div className="w-44">
                      <Image src={a7} alt="" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-1 flex flex-wrap">
              <div className="bg-[hsl(232,47%,28%)] w-full h-1 mt-[18px] rounded-2xl"></div>
              <Link
                href="/placements"
                className="absolute bg-gray-100 px-3 py-2 w-fit rounded-3xl text-center font-bold sm:left-[47%] left-[75%] hover:shadow-inside-shadow hover:scale-90 active:scale-110 transition-all duration-300"
              >
                Know More
              </Link>
            </div>
          </div>
          <div id="newsletter" className="mt-3">
            <AnimatedText
              text="News"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <News props={newslinks} />
          </div>
          <div
            id="activities"
            className="flex flex-wrap rounded-2xl mt-10 px-4 w-full "
          >
            <AnimatedText
              text="Student Activities"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)]"
            />
            <div>
              <p className="pb-1 font-sans font-medium text-lg">
                &emsp;&emsp;&emsp;The Comprehensive Curriculum at Academy of
                Technology creates space for various activities beyond the
                university prescribed syllabus. AOT organizes several seminars,
                industrial visits, invited lectures and national/international
                conferences on a regular basis to enhance the academic knowledge
                and professional competence of students. Renowned academicians
                and experts from top corporate firms visit the college to speak
                to the students about recent advancements in technology.
                Arrangement is also made to broadcast webinars relevant to the
                academic interests of the students.
              </p>
            </div>
          </div>
          <div>
            <Slidertext3d props={csephotos} />
          </div>
          <div
            id="faculty"
            className="flex flex-wrap rounded-2xl pt-4 px-4 w-full justify-center"
          >
            <AnimatedText
              text="Our Faculty"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <div className="mt-4">
              <div className="grid grid-cols-2 md:grid-cols-1 gap-6 w-full ">
                <Facultycard />
                <Facultycard />
              </div>
            </div>
          </div>
          <div
            id="staff"
            className="flex flex-wrap rounded-2xl pt-4 px-4 w-full justify-center"
          >
            <AnimatedText
              text="Our Staffs"
              className="!text-4xl text-center font-serif !text-[hsl(232,47%,28%)] italic"
            />
            <div className="mt-4">
              <div className="grid grid-cols-2 md:grid-cols-1 gap-6 w-full ">
                <Facultycard />
                <Facultycard />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};
export default cse;
