import React from 'react';
import Head from "next/head";
import Link from "next/link";
//import components
import Layout from "@/components/Layout";
import Nav from "@/components/navigation/Nav";
import Banner from "@/components/banner/Banner";
import AnimatedText from "@/components/AnimatedText";
//dictionary import
import { homebanner } from "@/dictionary/Bannerlist";


const research = () => {
  return (
    <>
      <Head>
        <title>AOT | Research</title>
        <meta name="description" content="Generated by me" />
      </Head>
      <Nav />
      <main className="flex w-full flex-col items-center justify-center">
        <Banner sliderItems={homebanner} />
        <Layout className="!pt-8">
          <div id="current-research">
          <AnimatedText text="Passion Fuels Purpose!" className="my-8" />
          <div className="flex flex-wrap bg-orange-500 rounded-2xl p-4 w-full">
            Nisi labore officia consectetur do ex Lorem dolore fugiat est consequat. Fugiat sint aute qui non. Mollit ullamco occaecat velit et commodo cillum deserunt dolor reprehenderit adipisicing. Deserunt magna aliquip minim dolore dolor consequat ipsum esse ut proident. Qui esse reprehenderit tempor ad ullamco commodo ullamco est exercitation nisi qui id. Nostrud occaecat eiusmod nostrud elit fugiat culpa deserunt dolor dolor elit deserunt incididunt. Incididunt aute do voluptate dolor irure cillum sint minim.
          </div>
          </div>
          <div id="past-research">
          <AnimatedText text="Passion Fuels Purpose!" className="my-8" />
          <div className="flex flex-wrap bg-orange-500 rounded-2xl p-4 w-full">
            Nisi labore officia consectetur do ex Lorem dolore fugiat est consequat. Fugiat sint aute qui non. Mollit ullamco occaecat velit et commodo cillum deserunt dolor reprehenderit adipisicing. Deserunt magna aliquip minim dolore dolor consequat ipsum esse ut proident. Qui esse reprehenderit tempor ad ullamco commodo ullamco est exercitation nisi qui id. Nostrud occaecat eiusmod nostrud elit fugiat culpa deserunt dolor dolor elit deserunt incididunt. Incididunt aute do voluptate dolor irure cillum sint minim.
          </div>
          </div>
          <div id="research-facilities">
          <AnimatedText text="Passion Fuels Purpose!" className="my-8" />
          <div className="flex flex-wrap bg-orange-500 rounded-2xl p-4 w-full">
            Nisi labore officia consectetur do ex Lorem dolore fugiat est consequat. Fugiat sint aute qui non. Mollit ullamco occaecat velit et commodo cillum deserunt dolor reprehenderit adipisicing. Deserunt magna aliquip minim dolore dolor consequat ipsum esse ut proident. Qui esse reprehenderit tempor ad ullamco commodo ullamco est exercitation nisi qui id. Nostrud occaecat eiusmod nostrud elit fugiat culpa deserunt dolor dolor elit deserunt incididunt. Incididunt aute do voluptate dolor irure cillum sint minim.
          </div>
          </div>
        </Layout>
      </main>
    </>
  )
}

export default research